### ISSUE TITLE
ApplicationToken#getActive always returns false

### ISSUE THREAD

**Issue by tom-myz** [gyro-n/gopay-java-sdk#10]
When I run following code,
```
  gyronPay.withLoginToken(loginToken).listAppTokens(new StoreId(storeId)).build()
  (*) gyronPay: GoPaySDK
```
any token is evaluated as inactive.

**Comment by justinian336** [comment]
It's weird because we're testing for this particular case here:

https://github.com/gyro-n/gopay-java-sdk/blob/488329ef5eb84889ee2b5d4731156b01209ca3a5/src/test/java/com/univapay/gopay/applicationtoken/GetAppTokenTest.java#L40

I tested with a Sync request but couldn't reproduce neither.

Are you sure that the application tokens were effectively active?

**Comment by tom-myz** [comment]
Ok, it may not be a SDK’s issue.

As far as I see 
https://github.com/ubicast/gyron-payments-api/blob/develop/core/src/main/scala/payments/formatters/model/ApplicationTokenFormatter.scala
`active` seems to be returned only on admin route.

We shouldn’t check it if it’s unclear that the user has the admin role or not, I think.
Thank you for your time.
